### ISSUE TITLE
Make a bookmarklett available

### ISSUE THREAD

**Issue by jeena** [notenoughneon/thready#2]
Make a bookmarklett available so people can drag and drop them into their bookmarks bar, just maka a link like this: `javascript:document.location.href="http://thready.notenoughneon.com/?url="+document.location.href` It's easier for people if they can just drag it, without having to write it on their own.

This way you can get the whole thread from whichever page you happen to be on, without the need of copy and pasting and remembering the url, etc.

**Comment by notenoughneon** [comment]
Cool idea! I haven't used bookmarklets but that sounds super useful.
